name: flutter_number_flow
description: A beautiful Flutter widget that animates number changes with smooth transitions. Perfect for animated counters, currency values, and statistics with locale support.
version: 0.1.0
homepage: https://github.com/example/flutter_number_flow
repository: https://github.com/example/flutter_number_flow
issue_tracker: https://github.com/example/flutter_number_flow/issues
documentation: https://pub.dev/documentation/flutter_number_flow/latest/

topics:
  - animation
  - counter
  - number
  - formatting
  - ui
  - material-design
  - widgets
  - flutter-widget
  - intl
  - locale

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: